Add hadolint and ShellCheck extension

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -13,12 +13,27 @@ RUN find /files -type d -exec chmod 755 {} \; \
   && find /files -type f -exec chmod 644 {} \; \
   && find /files/usr/local/bin -type f -exec chmod 755 {} \;
 
+FROM koalaman/shellcheck:stable as sci
+
 FROM ${BUILD_ON_IMAGE}:${PYTHON_VERSION}
 
 ARG DEBIAN_FRONTEND=noninteractive
 
+RUN dpkgArch="$(dpkg --print-architecture)" \
+  ## Install hadolint
+  && case "$dpkgArch" in \
+    amd64) tarArch="x86_64" ;; \
+    arm64) tarArch="arm64" ;; \
+    *) echo "error: Architecture $dpkgArch unsupported"; exit 1 ;; \
+  esac \
+  && apiResponse="$(curl -sSL \
+    https://api.github.com/repos/hadolint/hadolint/releases/latest)" \
+  && downloadUrl="$(echo "$apiResponse" | grep -e \
+    "browser_download_url.*Linux-$tarArch\"" | cut -d : -f 2,3 | tr -d \")" \
+  && echo "$downloadUrl" | xargs curl -sSLo /usr/local/bin/hadolint \
+  && chmod 755 /usr/local/bin/hadolint \
   ## Create folders in root directory
-RUN mkdir -p /root/.local/bin \
+  && mkdir -p /root/.local/bin \
   && mkdir -p /root/projects \
   ## Create folders in skeleton directory
   && mkdir -p /etc/skel/.local/bin \
@@ -63,3 +78,6 @@ ENV BUILD_DATE=
 
 ## Copy binaries as late as possible to avoid cache busting
 COPY --from=files /files /
+
+## Copy shellcheck as late as possible to avoid cache busting
+COPY --from=sci /bin/shellcheck /usr/local/bin/shellcheck
